id: vectorscan
name: VectorScan
owner: ''
version: 2.0.0
status: production
spec_yaml: ''
checklist_yaml: ''
gpt_instructions_yaml: ''
x_legacy:
  architecture:
    core_dependency_id: guardsuite-core@>=1.4.0,<2.0.0
    schema_source: guardsuite-core/canonical_schema.json
    required_interfaces:
    - I_Evaluator
    - I_ScannerCLI
    override_exclusion:
    - canonical.output_contract
    - evaluator.runtime_override
    output_contract: strict
  cli:
    base_command: vectorscan
    scan_command: vectorscan scan
    supported_flags:
    - --json
    - --stdin
    - --quiet
    - --explain
    - --output json
    reserved_flags:
    - --compliance-ledger
    - --fixpack-summary
  compliance:
    compliance_ledger_enabled: false
    ledger_visibility: none
  ecosystem_integrations:
    guardscore:
      pillar_weight: 0.33
      severity_penalties:
        critical: 40
        high: 25
        medium: 10
        low: 2
      provided_score_inputs:
      - issue_count_by_severity
      - remediation_hint_count
      - resource_count
      badge_eligibility_signal: true
    playground:
      wasm_safe: true
      max_runtime_ms: 2000
      playground_latency_target_ms: 1300
      json_sanitize: true
      svg_sanitize: true
      quick_score_mode: true
    guardboard:
      exposes_fixpack_hints: true
      shows_compliance_ledger: false
      badge_preview_supported: true
  features:
  - id: VEC-FEAT-001
    title: Public Endpoint Detection
    summary: Detects vector indices exposed to global CIDRs.
    included: true
  - id: VEC-FEAT-004
    title: Embedding Storage Encryption Check
    summary: Flags storage lacking encryption-at-rest.
    included: true
  - id: VEC-FEAT-020
    title: IAM Wildcard Detection
    summary: Detects IAM roles with unsafe vector path wildcards.
    included: true
  - id: VEC-FEAT-030
    title: Retrieval Pipeline Configuration Safety
    summary: Detects missing filters, PII omissions, or risky retrieval params.
    included: true
  fixpack:
    included: false
    reference_hint_format: fixpack:<ISSUE_ID>
    surfaces_hints: true
  future_extensions:
  - vector store cost estimation (lightweight mode)
  - embedding density heuristics
  - advanced retrieval pattern heuristics
  governance:
    spec_version: '2025.11'
    last_reviewed: '2025-11-24'
    owner: GuardSuite Platform Team
    stability_level: ga
  governance_domains:
  - embedding_security
  - network_exposure
  - encryption
  - iam_controls
  - retrieval_pipeline_safety
  - drift_detection
  - observability_gaps
  interoperability_conflicts:
  - QuickScore mode may require recalibration for GuardScore v2.
  - Embedding governance model expansion (2026) may introduce new fields.
  long_description: 'VectorScan provides fast, deterministic governance and security
    scanning

    for vector-serving infrastructure, embedding storage, and RAG

    configuration patterns. It emits canonical schema–aligned output,

    integrates seamlessly with Playground, and feeds GuardScore and

    GuardBoard for scoring and reporting. VectorScan is the top-of-funnel

    entry point into the GuardSuite ecosystem.

    '
  maintainers:
  - name: Deon Prinsloo
    role: AI Solutions Architect
    contact: deon@shieldcraft-ai.com
  - name: GuardSuite PMO
    role: Product Owner
    contact: pmo@shieldcraft-ai.com
  marketing:
    hero: Secure your vector stack with instant, deterministic scans.
    funnel_stage: bottom_funnel
    blurbs:
    - Detect embedding leaks and public vector endpoints
    - Perfect for Playground paste-to-scan
    - Upgrade to VectorGuard for remediation & ledger
    ctas:
    - text: Scan your plan now
      href: /playground
    ux_goals:
    - Scan GenAI apps for policy drift
    - Pipeline GuardBoard ingest artifacts
  metadata:
    version: '2025.11'
    funnel_stage: mid_funnel
    pricing_reference: pricing/guardsuite_pricing.yml
    ux_goals:
    - Offer instant, deterministic scans for vector teams
    - Drive upgrades into VectorGuard when remediation is needed
  performance_constraints:
    max_memory_mb: 150
    expected_runtime_ms: 500
    large_plan_runtime_ms: 1200
    playground_runtime_ms: 1300
    quickscore_threshold_resources: 1000
  pillar: vector
  product_type: free_scanner
  purpose_summary: Detect misconfigurations and exposure risks in vector-serving infrastructure.
  references:
    master_spec: docs/guardsuite_master_spec.md
    template_spec: templates/spec_page.md.j2
    canonical_schema: guardsuite-core/canonical_schema.json
    pricing_reference: pricing/guardsuite_pricing.yml
  related_products:
    - guardboard
    - guardscore
    - guardsuite-core
    - vectorguard
  release_metadata:
    release_channel: stable
    release_notes_url: https://shieldcraft-ai.com/guardsuite/vectorscan/releases/2.0.0
    published_date: '2025-11-19'
  rule_categories:
  - Embedding Security
  - Network Exposure & Boundary Controls
  - IAM Hardening
  - Storage Encryption
  - Retrieval Configuration Safety
  - Drift Detection
  - Operational Logging & Observability
  security:
    no_external_calls_at_runtime: true
    sanitize_all_inputs: true
    svg_sanitization: true
    wasm_compatible: true
    sandbox_requirement: Playground runtime must be WASM sandboxed
    safe_error_reporting: true
  short_description: 'Free, deterministic Terraform plan scanner for vector databases,
    embedding pipelines, and RAG-like architectures.

    '
  testing:
    unit_tests_required: true
    integration_tests_required: true
    snapshot_schema_test: true
    test_coverage_min_percent: 80
    ci_jobs:
    - validate_schema
    - unit
    - integration
    - snapshot_conformance
  versioning:
    semver: true
    core_dependency_pin: guardsuite-core@>=1.4.0,<2.0.0
    schema_version_pin: canonical_schema@1.0.0
    breaking_change_policy: 'Any breaking change MUST include a guardsuite-core RFC,
      updated schema, and coordinated release with VectorGuard.

      '
    spec_version: '2025.11'
    last_reviewed: '2025-11-23'
    stability_level: ga
