---
id: guardboard
name: GuardBoard
product_type: experience
pillar: ui
version: "1.0.1"
status: production

short_description: >
  Deterministic GuardSuite dashboard and export surface that visualizes validated
  artifacts, GuardScore outcomes, and badge readiness for executives and auditors.

long_description: |
  GuardBoard ingests canonical GuardSuite artifacts (scan outputs, GuardScore summaries,
  badge metadata, compliance ledgers) and renders deterministic dashboards,
  investigation workflows, and export bundles. It ensures every view references
  immutable artifact IDs, tracks provenance, and keeps signed exports ready for
  audits. GuardBoard is how customer teams, SREs, and executives review GuardSuite
  posture with confidence.

purpose_summary: >
  Provide an auditable, deterministic UI and export layer for GuardSuite artifacts
  with signed bundles, provenance tracking, and badge previews.

marketing:
  hero: "Deterministic GuardSuite dashboards for execs and auditors."
  blurbs:
    - "Signed exports and immutable artifact references"
    - "Unified view across scanners, GuardScore, and compliance ledgers"
    - "Ready-made overlays for exec briefings and audits"
  ctas:
    - text: "Explore GuardBoard"
      href: "/docs/guardboard"

metadata:
  version: "2025.11"
  funnel_stage: toplevel_funnel
  pricing_reference: "pricing/guardsuite_pricing.yml"
  ux_goals:
    - "Visualize GuardSuite artifacts with deterministic ordering"
    - "Generate signed exports that pass executive and audit reviews"

governance:
  spec_version: "2025.11"
  last_reviewed: "2025-11-24"
  owner: "GuardSuite Platform Team"
  stability_level: ga

related_products:
  - computeguard
  - computescan
  - pipelinescan
  - vectorscan
  - guardscore
  - guardsuite-specs

architecture:
  core_dependency_id: "guardsuite-core@>=1.4.0,<2.0.0"
  schema_source: "guardsuite-core/canonical_schema.json"
  required_interfaces:
    - "I_ArtifactIngestor"
    - "I_DashboardRenderer"
    - "I_SignedExportService"
  override_exclusion:
    - "canonical.output_contract"
  output_contract: "dashboard"

governance_domains:
  - artifact_provenance
  - dashboard_determinism
  - export_signing
  - badge_preview_integrity
  - role_based_access

rule_categories:
  - "Artifact Integrity"
  - "Dashboard Rendering"
  - "Export Signing"
  - "Role-Based Access"
  - "Badge Preview UX"

features:
  - id: GBOARD-FEAT-010
    title: "Deterministic Artifact Views"
    summary: "Every dashboard references immutable artifact IDs with provenance."
    included: true
  - id: GBOARD-FEAT-020
    title: "Signed Export Bundles"
    summary: "Produces signed, tamper-evident exports for audits and exec briefings."
    included: true
  - id: GBOARD-FEAT-030
    title: "Badge + GuardScore Overlays"
    summary: "Visualizes GuardScore, badge eligibility, and remediation progress."
    included: true

fixpack:
  included: false
  reference_hint_format: "fixpack:<ISSUE_ID>"
  surfaces_hints: false

compliance:
  compliance_ledger_enabled: true
  ledger_visibility: "full"

cli:
  base_command: "guardboard"
  scan_command: "guardboard scan --plan <plan.json>"
  supported_flags:
    - "--json"
    - "--output json"
  reserved_flags:
    - "--export-signed"

api:
  rest_endpoint: "https://api.shieldcraft-ai.com/guardboard"
  auth: "GuardSuite API token"

performance_constraints:
  max_memory_mb: 256
  expected_runtime_ms: 500
  playground_runtime_ms: 200
  large_plan_runtime_ms: 850
  quickscore_threshold_resources: 50

ecosystem_integrations:
  guardscore:
    pillar_weight: 0.0
    severity_penalties:
      critical: 40
      high: 25
      medium: 10
      low: 2
    provided_score_inputs:
      - badge_metadata
      - guardscore
      - percentile
    badge_eligibility_signal: true
  playground:
    wasm_safe: true
    max_runtime_ms: 0
    playground_latency_target_ms: 0
    json_sanitize: true
    svg_sanitize: true
    quick_score_mode: false
  guardboard:
    exposes_fixpack_hints: false
    shows_compliance_ledger: true
    badge_preview_supported: true

testing:
  unit_tests_required: true
  integration_tests_required: true
  snapshot_schema_test: true
  test_coverage_min_percent: 85
  ci_jobs:
    - validate_schema
    - unit
    - integration
    - visual_regression

versioning:
  semver: true
  spec_version: "2025.11"
  last_reviewed: "2025-11-24"
  stability_level: ga
  breaking_change_policy: >
    Dashboard schema changes require migration guides, signed-export verifier updates,
    and comms to GuardScore + GuardSpecs consumers.

future_extensions:
  - "Live incident overlays"
  - "Self-service GuardScore badge configuration"
  - "Deeper drilldowns into FixPack adoption"

security:
  no_external_calls_at_runtime: true
  sanitize_all_inputs: true
  svg_sanitization: true
  wasm_compatible: false
  sandbox_requirement: "All exports must be signed and verified before download."

maintainers:
  - name: "GuardSuite Platform Team"
    role: "Product Owner"
    contact: "platform@guardsuite.internal"

release_metadata:
  release_channel: "stable"
  release_notes_url: "https://shieldcraft-ai.com/guardsuite/guardboard/releases/1.0.1"
  published_date: "2025-11-24"

references:
  master_spec: "docs/guardsuite_master_spec.md"
  template_spec: "templates/spec_page.md.j2"
  canonical_schema: "guardsuite-core/canonical_schema.json"

integration_points:
  products_consuming:
    - guardscore
    - guard-specs
  playground:
    quick_score_mode_supported: false
    exposes_fixpack_hints: false
  dashboards:
    - "exec_overview"
    - "compliance_audit"
    - "badge_status"

provenance:
  - "Derived from GuardSuite Platform dashboard charter"
