---
id: pipelineguard
name: PipelineGuard
product_type: paid_blueprint
pillar: pipeline
version: "2.4.0"
status: production

short_description: >
  Enterprise CI/CD and supply-chain governance with deterministic remediation,
  compliance ledgering, provenance integrity enforcement, and premium GuardScore
  intelligence.

long_description: |
  PipelineGuard is the enterprise-grade governance and workflow-security
  blueprint for CI/CD. It enforces deterministic CI/CD policy, supply-chain
  provenance, hardened artifact lifecycles, signature validation, FixPack-Lite
  deterministic remediation, and a full compliance ledger with hash-chain
  integrity. The blueprint provides more than 600 workflow, runner, permission,
  and supply-chain integrity rules. It integrates with GuardBoard for visual
  governance insights, GuardScore for workflow and artifact risk scoring, and
  Playground WASM sandbox execution for CI-safe evaluator runs.

purpose_summary: >
  Provide deterministic governance, artifact integrity enforcement,
  rule-driven workflow security, provenance validation, and enterprise
  remediation across software supply chains and multi-cloud CI/CD pipelines.

marketing:
  hero: "Deterministic CI/CD governance with ledger-grade remediation."
  blurbs:
    - "600+ workflow, runner, provenance, and artifact integrity rules."
    - "Hash-chained compliance ledger with premium GuardScore insights."
    - "FixPack-Lite snippets deliver deterministic remediation for pipelines."
  ctas:
    - text: "Explore PipelineGuard"
      href: "/docs/products/pipelineguard"

metadata:
  version: "2026.04"
  funnel_stage: bottom_funnel
  pricing_reference: "pricing/guardsuite_pricing.yml"
  documentation_entrypoint: "docs/products/pipelineguard.md"
  ux_goals:
    - "Guarantee enterprise-grade CI/CD governance coverage."
    - "Expose explainable ledger + remediation artifacts for auditors."
    - "Integrate GuardScore inputs without nondeterministic drift."

governance:
  spec_version: "2026.04"
  last_reviewed: "2026-03-12"
  owner: "GuardSuite Platform Team"
  stability_level: ga
  release_channel: stable
  changelog_required: true
  codeowners_required: true
  rfc_required_for_major: true
  blueprint_inheritance: "pipelinescan@>=2.0"
  forbidden_overrides:
    - canonical.output_contract
    - evaluator.runtime_override
    - compliance.disable_ledger
    - fixpack.runtime_override
    - provenance.disable_validation
  breaking_change_policy: >
    Any breaking change to remediation semantics, compliance ledger schema,
    provenance fields, or scoring inputs requires a PipelineGuard RFC,
    downstream sync with GuardScore & GuardBoard, and coordinated template
    regeneration across GuardSuite-Template and GuardSuite Core.
  principles:
    - "Schema-first governance with fixed evaluator ordering."
    - "Deterministic remediation + ledgering beat performance shortcuts."
    - "Provenance and signature validation are always enforced."
  evaluator_pipeline_invariants:
    - "Evaluator MUST match template-defined stage ordering exactly."
    - "No random, local time, locale, or env-dependent branching."
    - "All timestamps MUST be normalized UTC ISO-8601 + Z."
    - "All numeric operations MUST use fixed_64 semantics."
    - "All outputs MUST serialize using canonical_json_utf8."
    - "Snapshot normalization MUST produce identical hashes across 3 runs."

related_products:
  - pipelinescan
  - guardscore
  - guardboard
  - computeguard
  - computescan


architecture:
  core_dependency_id: "guardsuite-core@>=2.4.0"
  canonical_schema_source: "schemas/pipelineguard/canonical_schema.json"
  required_interfaces:
    - I_Evaluator
    - I_ScannerCLI
    - I_ComplianceLedger
    - I_RemediationEngine
  output_contract: strict
  evaluator_pipeline:
    stages:
      - load_pipeline_manifest
      - hydrate_provenance
      - build_permission_graph
      - evaluate_rules
      - synthesize_remediation
      - canonicalize_output
      - persist_compliance_ledger
    invariants:
      - "Evaluator MUST match template-defined stage ordering exactly."
      - "No random, local time, locale, or env-dependent branching."
      - "All timestamps MUST be normalized UTC ISO-8601 + Z."
      - "All numeric operations MUST use fixed_64 semantics."
      - "All outputs MUST serialize using canonical_json_utf8."
      - "Snapshot normalization MUST produce identical hashes across 3 runs."

governance_domains:
  - workflow_permissions
  - supply_chain_integrity
  - artifact_governance
  - secret_management
  - runner_security
  - job_boundary_controls
  - drift_detection
  - observability_gaps
  - compliance_mapping
  - deterministic_remediation
  - pipeline_identity_spoofing_detection
  - artifact_promotion_chain_integrity

rule_categories:
  - "Workflow Permissions & Boundary Safety"
  - "Supply-Chain Provenance & Signature Enforcement"
  - "Artifact Hardening & Integrity Lifecycle Governance"
  - "Secret Boundary Enforcement & Exposure Detection"
  - "Runner & Executor Hardening"
  - "Job & Step Boundary Safety"
  - "Pipeline Drift / Misalignment Detection"
  - "Telemetry & Logging Gaps"
  - "Deterministic Remediation & FixPack-Lite"
  - "Identity Spoofing, Token Trust Chains, and Workflow Tampering"
  - "Artifact Promotion Chain Governance"

features:
  - id: PIPEG-FEAT-010
    title: "Full Pipeline Governance Coverage"
    summary: "600+ workflow, permission, provenance, and artifact rules."
    included: true
  - id: PIPEG-FEAT-020
    title: "Compliance Ledger"
    summary: "Audit-grade, hash-chained ledger with provenance links."
    included: true
  - id: PIPEG-FEAT-030
    title: "FixPack-Lite Remediation"
    summary: "Deterministic, CI-safe remediation snippets."
    included: true
  - id: PIPEG-FEAT-040
    title: "Premium GuardScore Inputs"
    summary: "Supply-chain and workflow risk signals for scoring."
    included: true
  - id: PIPEG-FEAT-050
    title: "Artifact Lifecycle Governance"
    summary: "End-to-end artifact signature & provenance validation."
    included: true
  - id: PIPEG-FEAT-060
    title: "Pipeline Identity Security"
    summary: "Token trust chain, actor impersonation, and identity drift rules."
    included: true

fixpack:
  included: true
  fixpack_folder: "fixpack/pipeline"
  snippet_count: 10
  reference_hint_format: "fixpack:<ISSUE_ID>"
  deterministic_ordering: true
  signature_required: true
  provenance_required: true
  cache_stability_required: true
  wasm_safe_snippets_required: true

compliance:
  compliance_ledger_enabled: true
  ledger_visibility: full
  ledger_schema_version: "1.0.1"
  ledger_invariants:
    - canonical_ordering
    - deterministic_timestamps
    - hash_chain_required
    - provenance_link_required
    - ledger_index_monotonic
    - shard_partition_consistent
    - ledger_entry_canonical_json_utf8

cli:
  base_command: "pipelineguard"
  scan_command: "pipelineguard scan"
  supported_flags:
    - "--json"
    - "--stdin"
    - "--quiet"
    - "--explain"
    - "--output json"
    - "--fixpack-summary"
    - "--compliance-ledger"
  reserved_flags:
    - "--ledger-only"
    - "--fixpack-diff"
  wasm_safe_required: true
  machine_parseable_help: true
  canonical_error_output_required: true

performance_constraints:
  max_memory_mb: 230
  expected_runtime_ms: 650
  large_plan_runtime_ms: 1500
  playground_runtime_ms: 1800
  quickscore_threshold_resources: 800
  pipeline_stage_budgets:
    discover_ci_sources_ms: 200
    provenance_verification_ms: 250
    permission_graph_build_ms: 150
    evaluate_rules_ms: 300
    remediation_synthesis_ms: 150
    canonicalize_output_ms: 150
    ledgers_write_ms: 120

ecosystem_integrations:
  guardscore:
    pillar_weight: 0.33
    severity_penalties:
      critical: 40
      high: 25
      medium: 10
      low: 2
    provided_score_inputs:
      - workflow_permission_risk
      - artifact_integrity_risk
      - remediation_hint_count
      - fixpack_applied_count
      - compliance_ledger_item_count
      - identity_drift_score
      - pipeline_complexity_score
    badge_eligibility_signal: true
  playground:
    wasm_safe: true
    max_runtime_ms: 2000
    playground_latency_target_ms: 1500
    json_sanitize: true
    svg_sanitize: true
    quick_score_mode: true
  guardboard:
    exposes_fixpack_hints: true
    shows_compliance_ledger: true
    advanced_score_overlays: true
    badge_preview_supported: true
    provenance_chain_insights: true

testing:
  unit_tests_required: true
  integration_tests_required: true
  snapshot_schema_test: true
  test_coverage_min_percent: 85
  wasm_conformance_required: true
  parity_tests_required: true
  evaluator_determinism_tests_required: true
  ci_jobs:
    - validate_schema
    - unit
    - integration
    - snapshot_conformance
    - parity_tests
    - wasm_conformance
    - evaluator_determinism

versioning:
  semver: true
  core_dependency_pin: "guardsuite-core@>=2.4.0"
  schema_version_pin: "canonical_schema@>=2.0.0"
  compatibility_window_months: 12
  breaking_change_process: "RFC + core + pipelinescan coordination"
  stability_level: ga

interoperability_conflicts:
  - "Unsigned pipelines or artifact promotion chains"
  - "Dynamic evaluator plugins with nondeterministic IO"
  - "Disabling compliance ledger persistence"

future_extensions:
  - "Signed remediation bundles for partner-led workflows"
  - "GuardScore percentile overlays inside GuardBoard"
  - "CI provider specific quickstart generators"

security:
  no_external_calls_at_runtime: true
  sanitize_all_inputs: true
  svg_sanitization: true
  provenance_required: true
  wasm_compatible: true
  sandbox_requirement: "Playground runtime must be WASI sandboxed"
  safe_error_reporting: true
  forbidden_overrides_enforced: true

maintainers:
  - name: "Deon Prinsloo"
    role: "AI Solutions Architect"
    contact: "deon@shieldcraft-ai.com"
  - name: "PipelineGuard Blueprint Team"
    role: "Product Owner"
    contact: "pipelineguard@guardsuite.internal"

release_metadata:
  release_channel: stable
  release_notes_url: "https://shieldcraft-ai.com/guardsuite/pipelineguard/releases/2.4.0"
  published_date: "2026-03-12"

references:
  canonical_schema: "schemas/pipelineguard/canonical_schema.json"
  pricing_reference: "pricing/guardsuite_pricing.yml"
  master_spec: "docs/guardsuite_master_spec.md"
  template_spec: "templates/spec_page.md.j2"
  deliverables:
    - schemas/pipelineguard/canonical_schema.json
    - fixpack/pipeline/*
    - cli/pipelineguard_cli.yaml
    - docs/runbooks/pipelineguard/*.md
    - examples/*
    - tests/pipelineguard/*
    - ci/pipelineguard-ci.yml

integration_points:
  guardboard:
    consumes_compliance_ledger: true
    renders_pipeline_heatmaps: true
  guardscore:
    ingests_pipeline_risk_signals: true
    exposes_fixpack_reduction_metrics: true
  pipelinescan:
    shares_evaluator_contracts: true
  playground:
    wasm_safe_runner: true

owner: "GuardSuite Platform Team"

spec_yaml: "products/pipelineguard.yml"
checklist_yaml: "checklists/pipelineguard.yml"
gpt_instructions_yaml: "templates/pipelineguard_instructions.yml"

provenance:
  - "Derived from PipelineGuard charter v2026.04"
  - "Aligned with canonical evaluator pipeline from guard-template"

products:
  - pipelineguard
