---
id: computescan
name: ComputeScan
product_type: free_scanner
pillar: compute
version: "1.0.0"
status: production

short_description: >
  Lightweight, deterministic compute resource scanner that feeds GuardSuite
  scoring, remediation, and dashboard products.

long_description: |
  ComputeScan discovers compute resources (VMs, instances, GPU attachments),
  evaluates sizing, cost, and telemetry posture, and emits canonical findings
  for downstream GuardSuite products. It prioritizes deterministic output,
  fast CI-friendly runtimes, and fixpack preview hooks for higher-level guards.

purpose_summary: >
  Provide fast CI-safe compute scanning, canonical findings, and fixpack preview
  inputs for ComputeGuard, GuardScore, and GuardBoard.

marketing:
  hero: "Deterministic compute governance scanner for GuardSuite."
  blurbs:
    - "Low-latency compute scanning for CI and pre-deploy checks"
    - "Canonical JSON findings + GuardBoard-ready metadata"
    - "Built-in fixpack preview hooks for paid Guard products"
  ctas:
    - text: "Run ComputeScan"
      href: "/playground"

metadata:
  version: "2025.11"
  funnel_stage: mid_funnel
  pricing_reference: "pricing/guardsuite_pricing.yml"
  ux_goals:
    - "Provide CI-safe compute scans with deterministic issue ordering"
    - "Feed paid Guard products with high-signal preview data"

governance:
  spec_version: "2025.11"
  last_reviewed: "2025-11-24"
  owner: "GuardSuite Platform Team"
  stability_level: ga

related_products:
  - computeguard
  - guardscore
  - guardboard

architecture:
  core_dependency_id: "guardsuite-core@>=1.4.0,<2.0.0"
  schema_source: "guardsuite-core/canonical_schema.json"
  required_interfaces:
    - "I_Evaluator"
    - "I_ScannerCLI"
  override_exclusion:
    - "canonical.output_contract"
    - "evaluator.runtime_override"
  output_contract: "strict"

governance_domains:
  - compute_resource_inventory
  - cost_governance
  - telemetry_gap_detection
  - fixpack_preview_readiness
  - deterministic_output

rule_categories:
  - "Resource Inventory & Drift"
  - "Cost & Sizing Controls"
  - "Telemetry & Observability"
  - "Fixpack Preview Hooks"
  - "Deterministic Output Contract"

features:
  - id: CSCAN-FEAT-001
    title: "Fast Scan Mode"
    summary: "Low-latency deterministic scan for CI and pre-deploy checks."
    included: true
  - id: CSCAN-FEAT-002
    title: "Full Scan Mode"
    summary: "Expanded analysis for deep compute inventories."
    included: true
  - id: CSCAN-FEAT-003
    title: "Telemetry Coverage Checks"
    summary: "Flags missing metrics/logging for critical nodes."
    included: true
  - id: CSCAN-FEAT-004
    title: "Fixpack Preview Hooks"
    summary: "Provides deterministic hints for paid Guard fixpacks."
    included: true

fixpack:
  included: false
  reference_hint_format: "fixpack:<ISSUE_ID>"
  surfaces_hints: true
  notes: "ComputeGuard and paid products supply remediation bundles."

compliance:
  compliance_ledger_enabled: false
  ledger_visibility: "none"

cli:
  base_command: "computescan"
  scan_command: "computescan scan"
  supported_flags:
    - "--json"
    - "--stdin"
    - "--quiet"
    - "--explain"
    - "--fast"
    - "--full"
  reserved_flags:
    - "--fixpack-summary"
    - "--telemetry-report"

performance_constraints:
  max_memory_mb: 120
  expected_runtime_ms: 300
  large_plan_runtime_ms: 950
  playground_runtime_ms: 1100
  quickscore_threshold_resources: 900

ecosystem_integrations:

  guardscore:
    pillar_weight: 0.33
    severity_penalties:
      critical: 40
      high: 25
      medium: 10
      low: 2
    provided_score_inputs:
      - resource_inventory_gaps
      - cost_regression_risk
      - telemetry_coverage_score
      - fixpack_preview_count
    badge_eligibility_signal: true

  playground:
    wasm_safe: true
    max_runtime_ms: 1500
    playground_latency_target_ms: 900
    json_sanitize: true
    svg_sanitize: true
    quick_score_mode: true

  guardboard:
    exposes_fixpack_hints: true
    shows_compliance_ledger: false
    badge_preview_supported: true

testing:
  unit_tests_required: true
  integration_tests_required: true
  snapshot_schema_test: true
  test_coverage_min_percent: 80
  ci_jobs:
    - validate_schema
    - unit
    - integration
    - snapshot_conformance
    - perf_regression

versioning:
  semver: true
  core_dependency_pin: "guardsuite-core@>=1.4.0,<2.0.0"
  schema_version_pin: "canonical_schema@1.0.0"
  breaking_change_policy: >
    Any change that alters canonical finding fields or CLI output requires a
    coordinated release with ComputeGuard and GuardBoard consumers.

interoperability_conflicts:
  - "New compute adapters may require GuardScore weighting refresh."
  - "Fixpack preview schema changes impact GuardBoard overlays."

future_extensions:
  - "GPU utilization governance heuristics"
  - "Deterministic capacity planning hints"
  - "Optional sustainability scoring inputs"

security:
  no_external_calls_at_runtime: true
  sanitize_all_inputs: true
  svg_sanitization: true
  wasm_compatible: true
  sandbox_requirement: "Playground runtime must be WASM sandboxed"
  safe_error_reporting: true

maintainers:
  - name: "Deon Prinsloo"
    role: "AI Solutions Architect"
    contact: "deon@shieldcraft-ai.com"

release_metadata:
  release_channel: "stable"
  release_notes_url: >-
    https://shieldcraft-ai.com/guardsuite/computescan/releases/1.0.0
  published_date: "2025-11-19"

references:
  master_spec: "docs/guardsuite_master_spec.md"
  template_spec: "templates/spec_page.md.j2"
  canonical_schema: "guardsuite-core/canonical_schema.json"

api:
  rest_endpoint: "https://api.shieldcraft-ai.com/computescan"
  auth: "GuardSuite API token"

integration_points:
  products_consuming:
    - computeguard
    - guardscore
    - guardboard
  playground:
    quick_score_mode_supported: true
