id: pipelinescan
name: ''
owner: ''
version: ''
spec_yaml: ''
checklist_yaml: ''
gpt_instructions_yaml: ''
x_legacy:
  acceptance_criteria:
  - All canonical artifacts validate against schemas and DET-001 normalization rules.
  - 'Snapshot determinism: 3-run identical hash under supported images.'
  - No remediation artifacts or fixpack content included in repository or outputs.
  - No core/binary artifacts packaged or referenced.
  - CLI help machine-parseable (--json) and CLI JSON outputs validate against canonical
    schema.
  - Parity tests (python ↔ wasm) pass for representative fixtures.
  - Adapters are WASM-safe and read-only; any failing adapter tests block merge.
  artifact_contract:
    canonical_output_schema: schemas/pipelinescan/canonical_output.json
    schema_version_pin: canonical_output@>=2.0.0
    required_fields:
    - metadata
    - issues[]
    - issues[].rule_id
    - issues[].resource_id_or_address
    - issues[].severity
    - pipeline_snapshot (optional)
    provenance:
      required: false
      recommended_for_high_confidence_checks: true
      rules:
      - if_provenance_present: validate_signature_if_present
      - missing_provenance: 'allowed (scanner sets provenance_source: "scanner_unverified")'
    export_bundle_contract:
      required_fields:
      - metadata
      - issues
      - guardscore_inputs_light
      - adapters_manifest
      canonical_serialization: true
      wasm_safe: true
      prohibits:
      - remediation_patches
      - fixpack_content
      - private_binary_references
  cli:
    base_command: pipelinescan
    scan_command: pipelinescan scan
    supported_flags:
    - --json
    - --stdin
    - --quiet
    - --explain
    - --out <path>
    reserved_flags:
    - --internal-debug
    exit_codes:
      VALIDATION_ERROR: 2
      RUNTIME_ERROR: 3
      SCHEMA_ERROR: 4
      PARTIAL_INPUT_ERROR: 5
    invariants:
    - help must be machine_parseable when --json supplied
    - CLI must not expose internal IP, remediation content, or binary references
    - CLI outputs must conform to canonical_output_schema when --json used
  deliverables:
  - repos/pipelinescan/spec.yml
  - schemas/pipelinescan/canonical_output.json
  - rules/pipelinescan/*.yml
  - adapters/*/manifest.yml
  - examples/scenarios/*
  - tests/snapshots/*
  - ci/pipelinescan-ci.yml
  determinism:
    normalization_layer: DET-001
    hashing_contract:
      algorithm: SHA256
      input: normalized_payload(strip_diagnostics_for_hash=true)
      serialization: canonical_json_utf8
      output_encoding: hex_lowercase
      fixed64_required: true
      cross_runtime_consistency: true
    snapshot_requirements:
      runs: 3
      cross_platform_images:
      - ubuntu-22.04
      - debian-12
      - macos-latest
      identical_hash_required: true
  evaluator_pipeline:
    source_of_truth: guardsuite-core:evaluator_pipeline_stages
    enforce_stage_ordering: true
    stages:
    - load_profile
    - initialize_context
    - load_schema
    - validate_schema
    - discover_ci_resources
    - gather_metadata
    - evaluate_rules
    - canonicalize_output
    - snapshot_normalize
    - emit_output
    invariants:
    - Stages must run in the listed order and be idempotent.
    - No nondeterministic IO, no runtime clock reads, no randomness inside stages.
    - No stage may attempt remediation or fixpack application.
    - Adapters must only collect read-only metadata and must be WASM-safe.
  examples_and_docs:
    examples_dir: examples/scenarios/
    required_example_count: 6
    docs_required:
    - docs/getting_started.md
    - docs/adapters.md
    - docs/security.md
    - docs/observability.md
  fixpack:
    included: false
    notes: 'PipelineScan does NOT execute or ship fixpacks. It may surface *hints*
      referencing paid fixpacks by **opaque ID only** (no patch content, no patch
      preview). Any reference must be an ID that resolves only within paid product
      pipelines.

      '
  governance_notes:
  - PipelineScan is a limited, detection-only scanner used to funnel users toward
    paid remediation products (PipelineGuard).
  - Ensure all contributor PRs are validated for forbidden content (remediation code,
    binary references).
  - Adapter PRs must include wasm safety evidence and a read-only manifest.
  guardboard_integration:
    expected_contract:
    - canonical_fields_present: true
    - badge_preview_eligible: true
    - fixpack_hints_referenced_by_id_only: true
    - compliance_ledger_integration: false
    visualization_guidance:
    - short_summary: Scanner-level summary suitable for engineering review
    - do_not_show_remediation_patches: true
  guardscore_integration:
    whitelist_inputs_allowed:
    - issue_count_by_severity
    - artifact_integrity_flag
    - workflow_permission_risk_light
    - resource_count
    forbidden_inputs:
    - remediation_confidence_points
    - estimated_reduction_points
    - fixpack_application_status
    penalty_map:
      critical: 40
      high: 25
      medium: 10
      low: 2
      info: 0
  metadata:
    id: pipelinescan
    name: PipelineScan
    product_type: free_scanner
    pillar: pipeline
    product_version: 2.4.0
    status: production
    owner: GuardSuite Platform Team
    maintainers:
    - name: Deon Prinsloo
      role: AI Solutions Architect
      contact: deon@shieldcraft-ai.com
    created: '2026-04-01'
    updated: '2026-04-15'
    summary: 'Lightweight, deterministic pipeline scanner for CI/CD manifests (GitHub
      Actions, GitLab CI, Terraform pipelines, container build workflows). Produces
      canonical, schema-first artifacts consumable by GuardScore and GuardBoard. Intentionally
      limited to detection + hints (no remediation content shipped). Designed to be
      WASM-safe and IP-preserving (no paid binaries or fixpack execution).

      '
      related_products:
      - guardsuite-core
  observability:
    metrics:
    - pipelinescan_runs_total
    - pipelinescan_issues_total
    - pipelinescan_partial_inputs_total
    logs:
      structured_json: true
      redact_fields:
      - resource_id
      - tenant_id
      - user_paste
      include:
      - spec_version
      - scanner_version
    telemetry_limits:
      max_event_payload_bytes: 16000
      max_events_per_scan: 50
      max_events_per_rule_execution: 5
  performance:
    runtime_target_ms: 400
    memory_cap_mb: 192
    stage_budgets:
      discover_ci_resources_ms: 150
      gather_metadata_ms: 200
      evaluate_rules_ms: 250
      canonicalize_ms: 100
  principles:
  - schema_first: true
  - deterministic: true
  - non_ip_exposing: true
  - no_remediation_execution: true
  - wasm_safe: true
  - no_nondeterministic_io: true
  - provenance_preferred_but_optional: true
  purpose:
    brief: 'Provide accessible, deterministic pipeline security and supply-chain scanning
      that emits canonical GuardSuite artifacts while protecting paid remediation
      IP.

      '
    goals:
    - deterministic canonical artifacts for downstream consumers
    - minimal, read-only adapters for CI platforms
    - strict no-remediation/no-binary policy to protect commercial IP
    - WASM-safe runtime compatibility for Playground demos and browser runs
  resource_capabilities:
    supports:
    - ci_platform_metadata: required
    - job_definition_parsing: required
    - permission_graph: optional
    - artifact_manifest_parsing: required
    - provenance_fields: optional
    - runner_meta: optional
    adapter_manifest_requirements:
    - name
    - provider
    - capabilities[]
    - capability_version
    - wasm_safe: true
    - read_only: true
    - forbidden_ops:
      - network_access
      - filesystem_write
      - env_write
  responsibility_boundary:
    provided_by_template:
    - evaluator_pipeline_stages
    - canonicalization rules (DET-001)
    - telemetry schemas
    - snapshot normalization contract
    provided_by_core:
    - canonical schema fragments
    - provenance schema
    - binary parity / ABI (not shipped)
    provided_by_pipelinescan:
    - read-only pipeline scanning rules
    - lightweight adapters (metadata collection only)
    - sample plans & examples
    forbidden_overrides:
    - core binary modules (disallowed to package or reference)
    - canonicalization primitives
    - evaluator pipeline order
    - reimplementation of paid remediation logic or fixpack runtime
  rule_system:
    rule_id_namespace: pipelinescan
    rules_must:
    - have rule_id (snake_case)
    - have severity in [critical, high, medium, low, info]
    - have title, description, rationale, and remediation_hint_id (opaque)
    - be deterministic in evaluation
    forbidden_rule_capabilities:
    - executing patches
    - invoking external remediation engines
    - shipping private fixpack logic
    baseline_requirements:
    - minimum_rule_count: 120
    - category_coverage:
      - workflow_permissions
      - artifact_integrity
      - secret_management
      - runner_security
      - drift_detection
    - rule_metadata_required:
      - severity
      - group
      - explain
  security:
    no_external_calls_at_runtime: true
    sanitize_all_inputs: true
    wasm_compatible: true
    forbid_ip_exposure_rules:
    - Do not include or distribute guardsuite-core binary artifacts
    - Do not include remediation snippets or fixpack patches
    - Do not expose internal ABI manifests
    telemetry_redaction:
      redact_patterns:
      - .*secret.*
      - .*token.*
      minify_user_pasted_code: true
      limit_event_payload_bytes: 16000
  testing:
    unit_tests_required: true
    integration_tests_required: true
    snapshot_tests_required: true
    snapshot_runs: 3
    parity_tests:
      python_vs_wasm_required: true
      python_vs_native_optional: true
    coverage_min_percent: 80
    ci_jobs:
    - validate_schema
    - unit
    - integration
    - snapshot
    - wasm_conformance
    - parity_checks
  versioning:
    semver: true
    spec_version: '2026.04'
    product_version: 2.4.0
    compatibility_window_months: 12
    core_dependency_pin: guardsuite-core@>=2.4.0,<3.0.0
    schema_version_pin: schemas/pipelinescan@>=2.0.0
    breaking_change_process: RFC + guardsuite-core coordination + downstream consumer
      notice
  wasm_safety:
    enforce: true
    forbidden_operations:
    - randomness
    - system_time
    - locale
    - filesystem_write
    - environment_variable_access
    - network_access
    - dynamic_imports
    adapter_requirements:
    - wasm_safe: true
    - read_only: true
