id: computeguard
name: ComputeGuard
owner: ''
version: 2.0.0
status: production
spec_yaml: ''
checklist_yaml: ''
gpt_instructions_yaml: ''
x_legacy:
  api:
    rest_endpoint: https://api.shieldcraft-ai.com/computeguard
    auth: GuardSuite API token
  architecture:
    core_dependency_id: guardsuite-core@>=1.4.0,<2.0.0
    schema_source: guardsuite-core/canonical_schema.json
    required_interfaces:
    - I_Evaluator
    - I_ScannerCLI
    - I_ComplianceLedger
    override_exclusion:
    - canonical.output_contract
    - evaluator.runtime_override
    - canonicalization_rules
    output_contract: strict
  cli:
    base_command: computeguard
    scan_command: computeguard scan
    supported_flags:
    - --json
    - --stdin
    - --quiet
    - --explain
    - --output json
    - --fixpack-summary
    - --compliance-ledger
    reserved_flags:
    - --ledger-only
    - --fixpack-diff
    output_contract:
      json_schema: /schemas/cli_output.json
    error_contract:
      json_schema: /schemas/cli_error.json
  compliance:
    compliance_ledger_enabled: true
    ledger_visibility: full
    ledger_schema_version: 1.0.0
  ecosystem_integrations:
    guardscore:
      pillar_weight: 0.33
      severity_penalties:
        critical: 40
        high: 25
        medium: 10
        low: 2
      provided_score_inputs:
      - gpu_waste_estimate
      - compute_cost_risk
      - remediation_hint_count
      - fixpack_applied_count
      - compliance_ledger_item_count
      - resource_count
      badge_eligibility_signal: true
    playground:
      wasm_safe: true
      max_runtime_ms: 2000
      playground_latency_target_ms: 1600
      json_sanitize: true
      svg_sanitize: true
      quick_score_mode: true
    guardboard:
      exposes_fixpack_hints: true
      shows_compliance_ledger: true
      badge_preview_supported: true
  features:
  - id: CMPG-FEAT-010
    title: Full Compute Governance Coverage
    summary: 600+ compute governance rules spanning GPU and cost controls.
    included: true
  - id: CMPG-FEAT-020
    title: Compliance Ledger
    summary: Generates audit-grade JSON ledgers for FinOps reviews.
    included: true
  - id: CMPG-FEAT-030
    title: FixPack-Lite Remediation
    summary: Deterministic HCL snippets for top misconfigurations.
    included: true
  - id: CMPG-FEAT-040
    title: Advanced GuardScore Inputs
    summary: Feeds premium GuardScore weighting for executive reporting.
    included: true
  - id: CMPG-FEAT-050
    title: Pipeline-aware Governance
    summary: Correlates compute signals with CI/CD and telemetry adapters.
    included: true
  fixpack:
    included: true
    fixpack_folder: fixpack/compute
    reference_hint_format: fixpack:<ISSUE_ID>
    surfaces_hints: true
    snippet_count: 10
  future_extensions:
  - GPU sustainability scoring
  - Automatic remediation bundle promotions
  - Pipeline-to-compute correlation heatmaps
  governance:
    spec_version: '2025.11'
    last_reviewed: '2025-11-24'
    owner: GuardSuite Platform Team
    stability_level: ga
  governance_domains:
  - finops_governance
  - gpu_capacity_planning
  - telemetry_gap_detection
  - compliance_ledgering
  - deterministic_remediation
  integration_points:
    products_consuming:
    - computescan
    - guardscore
    - guardboard
    playground:
      quick_score_mode_supported: true
      exposes_fixpack_hints: true
  interoperability_conflicts:
  - Ledger schema updates require GuardBoard overlay refresh.
  - New compute adapters may shift GuardScore weighting.
  long_description: 'ComputeGuard extends ComputeScan with enterprise-grade FinOps
    governance,

    deterministic FixPack-Lite remediation, and audit-ready compliance ledgers. It

    enforces cost controls for GPU fleets, emits GuardScore upgrades, and ships

    GuardBoard overlays so leadership can track remediation health. The blueprint

    emphasizes deterministic output, schema-first interfaces, and WASM-safe

    execution for Playground demos.

    '
  maintainers:
  - name: Deon Prinsloo
    role: AI Solutions Architect
    contact: deon@shieldcraft-ai.com
  marketing:
    hero: Eliminate GPU waste with deterministic compute governance.
    blurbs:
    - 600+ advanced compute governance and FinOps rules
    - Deterministic FixPack-Lite remediation and ledger outputs
    - GuardScore upgrades and GuardBoard overlays for exec-ready reports
    ctas:
    - text: Get ComputeGuard
      href: /buy/computeguard
  metadata:
    version: '2025.11'
    funnel_stage: bottom_funnel
    pricing_reference: pricing/guardsuite_pricing.yml
    ux_goals:
    - Deliver deterministic GPU governance packages for enterprise releases
    - Surface actionable remediation bundles for GuardBoard and GuardScore consumers
  performance_constraints:
    max_memory_mb: 260
    expected_runtime_ms: 850
    large_plan_runtime_ms: 2000
    playground_runtime_ms: 2100
    quickscore_threshold_resources: 800
  pillar: compute
  product_type: paid_blueprint
  purpose_summary: 'Provide deterministic cost governance, remediation hints, and
    compliance-grade ledgers across GPU and compute-intensive workloads.

    '
  references:
    master_spec: docs/guardsuite_master_spec.md
    template_spec: templates/spec_page.md.j2
    canonical_schema: guardsuite-core/canonical_schema.json
  related_products:
  - computescan
  - guardscore
  - guardboard
  release_metadata:
    release_channel: stable
    release_notes_url: https://shieldcraft-ai.com/guardsuite/computeguard/releases/2.0.0
    published_date: '2025-11-19'
  rule_categories:
  - GPU Provisioning & Utilization
  - Rightsizing & Instance Sizing
  - Autoscaling Safety
  - Cost Escalation Detection
  - Compliance Mapping
  - Deterministic Remediation
  security:
    no_external_calls_at_runtime: true
    sanitize_all_inputs: true
    svg_sanitization: true
    wasm_compatible: true
    sandbox_requirement: Playground runtime must be WASM sandboxed
  short_description: 'Enterprise FinOps governance and deterministic remediation for
    GPU-heavy compute estates.

    '
  testing:
    unit_tests_required: true
    integration_tests_required: true
    snapshot_schema_test: true
    test_coverage_min_percent: 85
    ci_jobs:
    - validate_schema
    - unit
    - integration
    - snapshot_conformance
    - perf_regression
  versioning:
    semver: true
    core_dependency_pin: guardsuite-core@>=1.4.0,<2.0.0
    schema_version_pin: canonical_schema@1.0.0
    breaking_change_policy: 'Any breaking change requires a guardsuite-core RFC, FinOps
      ledger migration note, and coordinated release with ComputeScan and GuardBoard.

      '
